- hosts: dev
  become: yes
  roles:
    - role: geerlingguy.java
      when: "ansible_os_family == 'RedHat'"
      java_packages:
        - java-1.8.0-openjdk
    - role: infopen.openjdk-jdk
    - role: gantsign.maven
